from operator import itemgetter
import numpy
from theano.compile.function_module import orig_function

__author__ = 'ommirandap'


# Asumo que recibo como input una lista
# [[str1_t1, str2_t1, str3_t1, ...], [str1_t2, str1_t2, ...], ...]
# Lista de set de palabras

MAX_TOPICS_PER_HOUR = 6
KEYWORDS_PER_TOPIC = 2
MATCH_NO = 3


def collect_keywords(groups_of_keywords, new_keywords):
    check_flag = 0

    if (len(groups_of_keywords) == 0):
        a = {}
        for each in new_keywords:
            a[each] = 1
        groups_of_keywords.append(a)
        return groups_of_keywords

    intersection_length = []
    for group in groups_of_keywords:
        orig_keywords = set(group.keys())
        common_keywords = orig_keywords.intersection(new_keywords)
        intersection_length.append(len(common_keywords))

    max_score_ind = intersection_length.index(max(intersection_length))

    if (intersection_length[max_score_ind] >= MATCH_NO):
        check_flag = 1
        for each in new_keywords:
            if each in groups_of_keywords[max_score_ind].keys():
                groups_of_keywords[max_score_ind][each] = \
                    groups_of_keywords[max_score_ind][each] + 1
            else:
                groups_of_keywords[max_score_ind][each] = 1

    if (check_flag == 0):
        a = {}
        for each in new_keywords:
            a[each] = 1
        groups_of_keywords.append(a)

    return groups_of_keywords


def getKeywords_fromHeadlines(list_of_tweets):
    # INPUT: lista de set de words
    groups_of_keywords = []
    # To list of list of words
    headlines = []

    for t in list_of_tweets:
        a = []
        for w in t:
            a.append(w)
        headlines.append(a)

    for i in range(len(headlines)):
        for j in range(len(headlines))[i + 1:]:
            if (i == j):
                continue
            struct = jaccard_similarity(headlines[i], headlines[j])
            if (struct['no_common_words'] < MATCH_NO):
                continue
            groups_of_keywords = collect_keywords(groups_of_keywords,
                                                  struct['common_words'])

    scores = []
    i = 0
    for group in groups_of_keywords:
        avg = 0
        for each_key in group.keys():
            avg = avg + group[each_key]
        scores.append(float(avg) / len(group.keys()))
        i = i + 1

    sorted_indices = numpy.argsort(scores)
    sorted_indices = sorted_indices[::-1]

    # for i in range(len(sorted_indices)):
    #    index = sorted_indices[i]
    #    print scores[index]
    #    for each_key in groups_of_keywords[index].keys():
    #        print each_key + ' ' + str(groups_of_keywords[index][each_key])

    return groups_of_keywords


def compare(e1, e2):
    '''
    e1 = {kw1: sc1, kw2: sc2}
    e2 = {kw3: sc3, kw4: sc4}
    '''
    score1 = sum(e1.values()) / len(e1.values())
    score2 = sum(e2.values()) / len(e2.values())

    return score2 - score1


def get_keywords(list_of_tweets):
    # INPUT: lista de sets de words
    groups = getKeywords_fromHeadlines(list_of_tweets)
    groups = sorted(groups, cmp = compare)

    if len(groups) > MAX_TOPICS_PER_HOUR:
        groups = groups[0:MAX_TOPICS_PER_HOUR]

    ret = []

    for g in groups:
        most_relevant_kws = sorted(g.iteritems(), key = itemgetter(1),
                                   reverse = True)
        ret.append(tuple(most_relevant_kws[0:KEYWORDS_PER_TOPIC]))

    return ret


def get_tweets_keywords(tweets):
    day_tweets = []
    day_keywords = []

    # For filename... eso significa que es por hora (?)
    day_keywords.append(get_keywords(t for t in tweets if len(t) > 0))
    day_tweets.extend(tweets)

    return (day_tweets, day_keywords)


def jaccard_similarity(sentence1, sentence2):
    # Calculo del indice de Jaccard. Inter versus Union
    # Esto no deberia tocarlo mas
    # words1 = set(sentence1.split(' '))
    # words2 = set(sentence2.split(' '))

    words1 = set(sentence1)
    words2 = set(sentence2)
    common = words1.intersection(words2)
    total = words1.union(words2)

    similarity_struct = {}
    similarity_struct['sim'] = len(common) / float(len(total))
    similarity_struct['no_common_words'] = len(common)
    similarity_struct['common_words'] = common

    return similarity_struct


def main():
    T = [
        {'crecio', 'economico', 'motor', 'mundial', 'reinstala', 'tercer',
         'trimestre'},
        {'astros', 'cuarta', 'deparan', 'horoscopo', 'sepa'},
        {'afroamericano', 'ahora', 'baleado', 'detalles', 'informe', 'joven',
         'policia', 'vez'},
        {'afroamericano', 'herido', 'baleado', 'detalles', 'joven',
         'policia', },
        {'estados', 'unidos', 'policia', 'bala', 'herido', 'afroamericano'},
        {'batman', 'comics', 'enfrenta', 'flash', 'increible', 'marvel',
         'superheroes', 'superman', 'trailer'},
        {'buenos', 'diario', 'dias', 'digital', 'leer', 'papel', 'pueden'},
        {'colegio', 'convertirse', 'educacional', 'prefirio', 'privado',
         'reforma', 'subvencionado'},
        {'amigos', 'apagada', 'asegurate', 'bien', 'campamento', 'fogata',
         'hacen', 'informate', 'previene', 'quede', 'sales'},
        {'condiciones', 'consciente', 'escuches', 'gusta', 'musica', 'siempre',
         'subas', 'transito', 'volumen'},
        {'afroamericano', 'disparos', 'eeuu', 'informa', 'joven', 'muere',
         'policia'},
        {'buenos', 'diario', 'dias', 'digital', 'leer', 'papel', 'pueden'},
        {'aseguradora', 'delito', 'investigada', 'posible', 'usura'},
        {'alcohol', 'bajo', 'conducir', 'detenido', 'efectos', 'jugador',
         'manchester', 'united'},
        {'britanicos', 'critican', 'fisica', 'imagen', 'medicos', 'pascuero',
         'proyecta', 'viejo'},
        {'hombre', 'mata', 'missouri', 'negro', 'policia', 'unidos'},
        {'interior', 'viaje', 'yihadismo'},
        {'ano', 'asegura', 'buses', 'estudio', 'nuev', 'pasajes', 'triplicaran',
         'valor', 'visperas'},
        {'co2', 'companias', 'emiten', 'mundial', 'total'},
        {'candidato', 'eludir', 'pinera', 'potencia', 'presidente', 'pri',
         'puede'},
    ]

    T2 = [{'crecio',
           'economico',
           'motor',
           'mundial',
           'reinstala',
           'tercer',
           'trimestre'},
          {'astros', 'cuarta', 'deparan', 'horoscopo', 'sepa'},
          {'afroamericano',
           'ahora',
           'baleado',
           'detalles',
           'informe',
           'joven',
           'policia',
           'vez'},
          {'batman',
           'comics',
           'enfrenta',
           'flash',
           'increible',
           'marvel',
           'superheroes',
           'superman',
           'trailer'},
          {'buenos', 'diario', 'dias', 'digital', 'leer', 'papel', 'pueden'},
          {'colegio',
           'convertirse',
           'educacional',
           'prefirio',
           'privado',
           'reforma',
           'subvencionado'},
          {'amigos',
           'apagada',
           'asegurate',
           'bien',
           'campamento',
           'fogata',
           'hacen',
           'informate',
           'previene',
           'quede',
           'sales'},
          {'condiciones',
           'consciente',
           'escuches',
           'gusta',
           'musica',
           'siempre',
           'subas',
           'transito',
           'volumen'},
          {'afroamericano', 'disparos', 'eeuu', 'informa', 'joven', 'muere',
           'policia'},
          {'buenos', 'diario', 'dias', 'digital', 'leer', 'papel', 'pueden'},
          {'aseguradora', 'delito', 'investigada', 'posible', 'usura'},
          {'alcohol',
           'bajo',
           'conducir',
           'detenido',
           'efectos',
           'jugador',
           'manchester',
           'united'},
          {'britanicos',
           'critican',
           'fisica',
           'imagen',
           'medicos',
           'pascuero',
           'proyecta',
           'viejo'},
          {'hombre', 'mata', 'missouri', 'negro', 'policia', 'unidos'},
          {'interior', 'viaje', 'yihadismo'},
          {'ano',
           'asegura',
           'buses',
           'estudio',
           'nuev',
           'pasajes',
           'triplicaran',
           'valor',
           'visperas'},
          {'co2', 'companias', 'emiten', 'mundial', 'total'},
          {'candidato', 'eludir', 'pinera', 'potencia', 'presidente', 'pri',
           'puede'},
          {'diccionario',
           'digitales',
           'director',
           'nativos',
           'nuevo',
           'proximo',
           'proyecto',
           'rae'},
          {'lasarte', 'martin', 'plantel', 'premia'},
          {'arturo',
           'credibilidad',
           'cut',
           'futuro',
           'jugando',
           'laboral',
           'martinez',
           'reforma'},
          {'amigos',
           'claramente',
           'condena',
           'fiscal',
           'juan',
           'larrain',
           'martin',
           'mintieron',
           'pablo',
           'pereira'},
          {'antecedentes',
           'entrevista',
           'fiscal',
           'horas',
           'influencia',
           'juan',
           'pablo',
           'pereira'},
          {'ahora',
           'fiscal',
           'juan',
           'juicio',
           'larrain',
           'martin',
           'pablo',
           'pereira',
           'refiere'},
          {'agosto',
           'ano',
           'atenderia',
           'clinica',
           'inicia',
           'nunoa',
           'obras',
           'pacientes',
           'proximo'},
          {'alumnos', 'estafa', 'grange', 'remece'},
          {'12deg', '30deg', 'maxima', 'minima', 'sera'},
          {'dirigentes',
           'escuela',
           'formacion',
           'inedita',
           'lanzamiento',
           'prepara',
           'sindicales'},
          {'bolivia',
           'chile',
           'confirmada',
           'embajadora',
           'papa',
           'roma',
           'vaticano',
           'visita'},
          {'abe',
           'apuesta',
           'consolidar',
           'continuidad',
           'economico',
           'japon',
           'ministerial',
           'programa',
           'shinzo'},
          {'amor', 'arroz', 'diario', 'encuentre', 'leche', 'pop', 'verdadero'},
          {'alimento',
           'ayudar',
           'bajar',
           'comida',
           'espirulina',
           'moda',
           'peso',
           'promete',
           'sufren'},
          {'ciudadania', 'errazuriz', 'josefa', 'pedir', 'perdon', 'quiero'},
          {'2014', 'descubiertas', 'especies', 'extranas', 'fotos'},
          {'24horas', 'celebran', 'chile', 'inmigrantes', 'navidad'},
          {'conversa', 'pablo', 'sacerdote', 'walker'},
          {'anos', 'bebesol', 'despues', 'identidad', 'leido', 'revela',
           'teletubbies'},
          {'buenos',
           'cielos',
           'despejados',
           'dias',
           'espera',
           'grados',
           'hoy',
           'maxima',
           'rancagua'},
          {'ciudadania',
           'errazuriz',
           'josefa',
           'municipalidad',
           'pedir',
           'perdon',
           'quiero',
           'uso'},
          {'afroamericano',
           'arrestos',
           'cercanias',
           'ferguson',
           'joven',
           'masivos',
           'muerte',
           'policia',
           'realiza',
           'tras'},
          {'banda', 'exitosa', 'integrante', 'internan', 'sobredosis'},
          {'canales',
           'fiscal',
           'juicio',
           'muerte',
           'nuevo',
           'pereira',
           'posible',
           'recurrir'},
          {'barnechea',
           'casa',
           'detalles',
           'embajadora',
           'habrian',
           'robado',
           'sujetos'},
          {'aislada',
           'arcos',
           'ataca',
           'comunidades',
           'flechas',
           'informe',
           'peru',
           'tribu'},
          {'app', 'comienza', 'mundo', 'puedes', 'seguir', 'viaje'},
          {'afroamericano', 'disparos', 'eeuu', 'informa', 'joven', 'muere',
           'policia'},
          {'2015', 'analiza', 'colo', 'hector', 'tapia', 'video'},
          {'apropiacion',
           'cerro',
           'cmr',
           'cruzat',
           'enfrento',
           'falabella',
           'grupo',
           'indebida',
           'litigio',
           'millonaria'},
          {'continuara', 'leonardo', 'palestino', 'telefono', 'valencia',
           'video'},
          {'catolica',
           'mario',
           'movimiento',
           'plantel',
           'pone',
           'salas',
           'universidad',
           'video'},
          {'ano',
           'autoridades',
           'carreteras',
           'contingencia',
           'fiestas',
           'fin',
           'plan',
           'presentaron',
           'transporte'},
          {'bachelet',
           'cancilleria',
           'confirma',
           'cristina',
           'fernandez',
           'posible',
           'vaticano',
           'viaje'},
          {'argentina',
           'chile',
           'complementario',
           'firman',
           'maipu',
           'ministros',
           'protocolo',
           'tratado'},
          {'beneficiarios',
           'cobrados',
           'cuenta',
           'depositaran',
           'miles',
           'millones',
           'rut',
           'sido'},
          {'ahora',
           'cierran',
           'conductores',
           'escuela',
           'investigacion',
           'noticias',
           'tras'},
          {'amplias',
           'consumo',
           'costos',
           'creditos',
           'detecta',
           'diferencias',
           'sernac'},
          {'asistir',
           'confirmo',
           'francisco',
           'gobieno',
           'invitacion',
           'papa',
           'presidenta',
           'vaticano'},
          {'atacama',
           'cumple',
           'desaparicion',
           'guia',
           'mes',
           'pedro',
           'san',
           'turistico'},
          {'ataques',
           'constantes',
           'francia',
           'refuerza',
           'seguridad',
           'supuestos',
           'terroristas',
           'tras'},
          {'amigo', 'politicos', 'regalo', 'revelan', 'secreto', 'seria'},
          {'buena',
           'chilenos',
           'compartiran',
           'mas',
           'necesitados',
           'noche',
           'solidarios'},
          {'absolucion', 'conoce', 'definitiva', 'larrain', 'martin'},
          {'cerro',
           'expone',
           'graves',
           'licitacion',
           'lucia',
           'mantencion',
           'medio',
           'polemica',
           'problemas',
           'santa'},
          {'buena',
           'hola',
           'horas',
           'hoy',
           'llegue',
           'noche',
           'publimetro',
           'saludamos'},
          {'500', 'parece', 'trineo', 'via', 'video'},
          {'accidente',
           'bmw',
           'callejera',
           'carrera',
           'porsche',
           'termina',
           'tremendo',
           'via',
           'video'},
          {'avion', 'captura', 'coalicion', 'derriba', 'islamico', 'piloto',
           'siria'},
          {'160',
           'batros',
           'camino',
           'congestion',
           'coronel',
           'gran',
           'hora',
           'puente',
           'ruta'},
          {'joven', 'mata', 'misuri', 'negro', 'policia'},
          {'afecta',
           'asalto',
           'barnechea',
           'comuna',
           'embajadora',
           'libano',
           'violento'},
          {'antiyihadistas', 'atentado', 'combatientes', 'irak', 'muertos'},
          {'atencion', 'chacabuco', 'concepcion', 'malo', 'salas', 'semaforo'},
          {'abe',
           'japones',
           'mayoria',
           'ministro',
           'parlamento',
           'primer',
           'reelige',
           'shinzo'},
          {'400',
           'denuncia',
           'detenciones',
           'gracias',
           'mas',
           'plan',
           'posibles',
           'seguro',
           'sido'},
          {'clausura', 'debut', 'equipos', 'futbol', 'grandes', 'movidas',
           'ultimas'},
          {'ahi',
           'artistas',
           'canciones',
           'lio',
           'quieren',
           'tener',
           'videos',
           'youtube'},
          {'ataques', 'aumenta', 'fin', 'francia', 'nerviosismo', 'semana',
           'tras'},
          {'funerales', 'hacen', 'indigentes', 'portugal', 'voluntarios'},
          {'actividades', 'distintas', 'miercoles', 'navidad', 'sepalo',
           'vispera'},
          {'auto',
           'chofer',
           'encima',
           'pasa',
           'pelea',
           'protagonizar',
           'transantiago',
           'tras',
           'video'},
          {'afecto', 'anos', 'asiatico', 'sudeste', 'tsunami'},
          {'ano', 'bottinelli', 'dario', 'mas', 'renovo'},
          {'chilenos', 'convirtieron', 'detras', 'historias', 'islam', 'video'},
          {'chile',
           'informate',
           'participa',
           'preparado',
           'preparate',
           'programa',
           'simulacros',
           'terremoto',
           'tsunami'},
          {'ano',
           'carabineros',
           'controles',
           'mas',
           'millones',
           'preventivos',
           'realiza',
           'total'},
          {'concretara', 'diego', 'forlan', 'oferta', 'universitario'},
          {'direction', 'fallon', 'jimmy', 'one', 'particular', 'video',
           'villancico'},
          {'apuesta', 'expansion', 'fernando', 'fundacion', 'gonzalez'},
          {'200', 'cines', 'eeuu', 'interview', 'mas', 'proyectaran', 'the'},
          {'acusado', 'carabineros', 'detuvo', 'hombre', 'joven', 'reina',
           'violar'},
          {'2015', 'clausura', 'fixture', 'leido', 'torneo'},
          {'alto', 'caer', 'canal', 'fallecio', 'joven', 'puente', 'regadio',
           'tras'},
          {'alexis',
           'felicitaciones',
           'lucio',
           'piano',
           'recibio',
           'sanchez',
           'tocando',
           'videofoto'},
          {'alrededor', 'mundo', 'pascuero', 'recorrido', 'sigue', 'viejito',
           'vivo'},
          {'conversar', 'estudios', 'hoy', 'regresa'},
          {'aqui',
           'atencion',
           'cambio',
           'carreteras',
           'desvios',
           'detalles',
           'flujo',
           'via'},
          {'afroamericano', 'disparos', 'eeuu', 'informa', 'joven', 'muere',
           'policia'},
          {'ano',
           'distinto',
           'inicia',
           'llevando',
           'miercoles',
           'mundo',
           'sonrisas',
           'unico',
           'viaje',
           'viejito'},
          {'caseros', 'cuatro', 'mas', 'preocupes', 'remedios'},
          {'caseros', 'cuatro', 'mas', 'preocupes', 'remedios'},
          {'clausura', 'debut', 'equipos', 'futbol', 'grandes', 'movidas',
           'ultimas'},
          {'ahi',
           'artistas',
           'canciones',
           'lio',
           'quieren',
           'tener',
           'videos',
           'youtube'},
          {'caseros', 'cuatro', 'mas', 'preocupes', 'remedios'},
          {'artificiales',
           'carabineros',
           'comercializados',
           'ferias',
           'fuegos',
           'incauta',
           'navidenas',
           'via'},
          {'2014', 'diciembre', 'horoscopo', 'hoy', 'miercoles', 'revisa'},
          {'caseros', 'cuatro', 'mas', 'preocupes', 'remedios'},
          {'caseros', 'cuatro', 'mas', 'preocupes', 'remedios'},
          {'caseros', 'cuatro', 'mas', 'preocupes', 'remedios'},
          {'00hrs',
           'centro',
           'desea',
           'diario',
           'especialmente',
           'excelente',
           'felicidades',
           'onomastico',
           'saluda'},
          {'caida', 'cima', 'posible', 'reo'},
          {'acto', 'asume', 'mandato', 'morales', 'presidenta', 'resta',
           'tercer'},
          {'division',
           'espana',
           'francisco',
           'jugar',
           'podria',
           'primera',
           'silva',
           'volver'},
          {'accidente',
           'alta',
           'ciudad',
           'congestion',
           'cristobal',
           'direccion',
           'empresarial',
           'huechuraba',
           'produce',
           'salida',
           'san',
           'tunel'},
          {'antiyihadista',
           'avion',
           'capturo',
           'coalicion',
           'derribo',
           'grupo',
           'islamico',
           'piloto',
           'siria'},
          {'colo', 'habla', 'vuelve'},
          {'amazon', 'compite', 'dia', 'entregas', 'fiestas', 'google',
           'mismo'},
          {'caso', 'gutierrez', 'roberto'},
          {'biografo',
           'curia',
           'desconcertada',
           'francisco',
           'mayoria',
           'papa',
           'pontifice'},
          {'12deg', '30deg', 'maxima', 'minima', 'sera'},
          {'celulas',
           'crecer',
           'descubren',
           'hacer',
           'inmune',
           'pelo',
           'pueden',
           'sistema',
           'tipo'},
          {'cuatro',
           'luego',
           'meses',
           'negociaciones',
           'paz',
           'prorrusos',
           'rebeldes',
           'reinician',
           'ucrania'},
          {'cuatro', 'decadas', 'marcelo', 'matador', 'salas'},
          {'absuelven', 'amigos', 'condenan', 'obstruccion', 'visto'},
          {'calendario',
           'erotismo',
           'lanza',
           'rapera',
           'recurriendo',
           'sigue',
           'visto'},
          {'afroamericano',
           'cerca',
           'dispara',
           'estadounidense',
           'ferguson',
           'mata',
           'policia',
           'visto'},
          {'alexis',
           'canciones',
           'felicita',
           'interpretar',
           'marx',
           'piano',
           'sanchez',
           'vistorichard'},
          {'cae', 'feroz', 'incendio', 'lolo', 'terneado', 'valparaiso'},
          {'alexis', 'hablando', 'llego', 'marcelo', 'salas', 'sanchez'},
          {'anggeli', 'conoce', 'dia', 'fernandez'},
          {'anotaste', 'chorizo', 'micrero', 'nuevo', 'patente', 'viral'},
          {'alejandra', 'alucina', 'diaz', 'duendes', 'pascueros'},
          {'agote',
           'corra',
           'cuarta',
           'diciembre',
           'disponible',
           'ejemplar',
           'portada'},
          {'agote',
           'corra',
           'cuarta',
           'diciembre',
           'disponible',
           'ejemplar',
           'portada'},
          {'ahora',
           'choque',
           'congestion',
           'cristobal',
           'gran',
           'interior',
           'registra',
           'salida',
           'san',
           'tunel'},
          {'atrevido', 'disfraz', 'espera', 'navidad', 'video'},
          {'absuelto', 'cauquenes', 'entrevista', 'explica', 'fiscal'},
          {'felicitacion',
           'inesperada',
           'mostrar',
           'piano',
           'recibio',
           'talento',
           'tras',
           'via'},
          {'cobrar', 'datos', 'ingresa', 'mas', 'mil', 'millones'},
          {'cerveza', 'ciencia', 'detras', 'fabricacion', 'informe', 'secreta'},
          {'app', 'mundo', 'navidena', 'recorrido', 'sigue', 'vivo'},
          {'espacio',
           'impresionante',
           'meses',
           'paisajes',
           'registro',
           'resume',
           'seis',
           'terrestres',
           'video'},
          {'alto',
           'congestion',
           'flujo',
           'hacia',
           'isabel',
           'norte',
           'salesianos',
           'salida',
           'santa',
           'vehicular'},
          {'copsa',
           'fin',
           'largo',
           'llamado',
           'planificar',
           'presidente',
           'realizo',
           'semana',
           'viajes'},
          {'canales',
           'estabamos',
           'hermana',
           'hernan',
           'peleando',
           'persona',
           'poderosa',
           'sabiamos'},
          {'alcala',
           'cierra',
           'dar',
           'diciembre',
           'inmobiliario',
           'paso',
           'proyecto',
           'puertas',
           'sabado',
           'teatro'},
          {'automovilista',
           'chofer',
           'destruido',
           'pelea',
           'termina',
           'transantiago',
           'vehiculo'},
          {'colo', 'ecuatoriano', 'mundialista', 'podria', 'reforzarse'},
          {'anticipada',
           'cerrar',
           'comercio',
           'debera',
           'diciembre',
           'forma',
           'puertas'},
          {'600',
           'central',
           'contingencia',
           'estacion',
           'mil',
           'pasajeros',
           'plan',
           'saldran',
           'terminales'},
          {'bush', 'debio', 'george', 'hospitalizado', 'padre', 'urgencia'},
          {'avion', 'captura', 'coalicion', 'derriba', 'islamico', 'piloto',
           'siria'},
          {'alto',
           'anos',
           'caer',
           'canal',
           'fallece',
           'menor',
           'puente',
           'regadio',
           'tras'},
          {'mundo', 'pascuero', 'sigue', 'viaje', 'viejito', 'vivo'},
          {'aqui',
           'climaticas',
           'condiciones',
           'esperan',
           'informe',
           'jornada',
           'revisa',
           'tiempo'},
          {'asaltan', 'barnechea', 'delincuentes', 'embajada', 'libano'},
          {'afroamericano', 'joven', 'mata', 'missouri', 'policia'},
          {'claus', 'fotos', 'habian', 'nunca', 'santa', 'visto'},
          {'conviene', 'decirle', 'edad', 'ninos', 'pascuero', 'verdad',
           'viejito'},
          {'aerolinea',
           'cumple',
           'deseos',
           'dominicana',
           'humilde',
           'navidad',
           'pueblo',
           'republica',
           'via',
           'video'},
          {'cal', 'canto', 'evacuacion', 'genera', 'linea', 'metro',
           'retrasos'},
          {'anecdotas', 'chileno', 'pascuero', 'santa', 'universidad',
           'viejito'},
          {'acceso', 'cerrado', 'ciudad', 'empresarial'},
          {'fotos', 'memes', 'navidad', 'perder', 'pueden'},
          {'harry', 'potter', 'protagonista', 'revela', 'rowling', 'secretos'},
          {'adolescente',
           'alto',
           'canal',
           'cayo',
           'fallecio',
           'grave',
           'moto',
           'pareja',
           'puente',
           'regadio'},
          {'alexis',
           'autor',
           'cancion',
           'felicitaciones',
           'gano',
           'interpreto',
           'piano'},
          {'absolucion', 'conoce', 'definitiva', 'larrain', 'martin'},
          {'adorables', 'famosos', 'mascotas'},
          {'acudira',
           'bachelet',
           'bolivia',
           'cambio',
           'evo',
           'mando',
           'morales',
           'presidenta'},
          {'belen',
           'crecio',
           'encanto',
           'graduacion',
           'nina',
           'papi',
           'recuerdas',
           'ricky',
           'soto',
           'vestido'},
          {'cosas', 'demas', 'hagan', 'odiamos', 'whatsapp'},
          {'caso',
           'companeros',
           'complica',
           'diaz',
           'marcelo',
           'nacionalidades',
           'suiza',
           'zarate'},
          {'5475',
           '98139',
           'avisar',
           'ayer',
           'ayuda',
           'carreracumming',
           'frente',
           'perdio',
           'perrito',
           'quilpue',
           'ripley'},
          {'ano', 'claves', 'fiestas', 'fin', 'intoxicacion', 'prevenir'},
          {'alemania', 'aumenta', 'movimiento', 'oposicion', 'pegida',
           'xenofobo'},
          {'acceso',
           'auto',
           'botado',
           'ciudad',
           'dejo',
           'empresarial',
           'http',
           'ojo',
           'pastel',
           'pata'},
          {'barrios',
           'busca',
           'estacion',
           'feria',
           'pinto',
           'proyecto',
           'reconocer',
           'temuco',
           'tipicas',
           'tucapel',
           'zonas'},
          {'560', 'arrasado', 'cerca', 'hectareas', 'hijuelas', 'incendio'},
          {'acudira',
           'filtracion',
           'fotos',
           'intimas',
           'justicia',
           'masterchef',
           'participante'},
          {'choque',
           'ciudad',
           'direccion',
           'empresarial',
           'huechuraba',
           'informamos',
           'salida',
           'vehiculo'},
          {'insurgentes', 'kiev', 'miercoles', 'negociaciones', 'paz',
           'reanudan'},
          {'2015',
           'adrenalina',
           'eje',
           'noche',
           'parte',
           'preparan',
           'reinas',
           'segunda'},
          {'cuestionamientos',
           'falencias',
           'farmaceuticos',
           'farmacos',
           'gremios',
           'ley',
           'reiteran'},
          {'escalada',
           'gaza',
           'israelies',
           'medio',
           'palestino',
           'soldados',
           'ultiman',
           'violencia'},
          {'acumulados',
           'anos',
           'beneficios',
           'depositaran',
           'hoy',
           'jovenes',
           'mujeres',
           'reclamados',
           'sido'},
          {'busca',
           'fisco',
           'fraude',
           'prescripcion',
           'querella',
           'rysselberghe',
           'van'},
          {'bancada', 'boric', 'causa', 'juvenil', 'rebelde', 'sobresale'},
          {'bush',
           'george',
           'hospitalizado',
           'presidente',
           'problemas',
           'respiratorios'},
          {'celebran', 'cristianos', 'navidad', 'ruinas', 'sirios'},
          {'ano',
           'destaca',
           'ingles',
           'jugadores',
           'medio',
           'mejores',
           'sanchez',
           'vidal'},
          {'alta',
           'choque',
           'congestion',
           'cristobal',
           'provoca',
           'san',
           'tunel',
           'vehiculos'},
          {'corea', 'funciona', 'internet', 'norte'},
          {'chilenos',
           'endeudarse',
           'hogares',
           'menos',
           'segundo',
           'tendieron',
           'trimestre'},
          {'151',
           'abarca',
           'comunas',
           'cuadrante',
           'info',
           'largo',
           'mas',
           'pais',
           'plan',
           'preventiva',
           'sabias',
           'seguridad'},
          {'antirrobos',
           'campana',
           'carabineros',
           'cuidadores',
           'junto',
           'preventiva',
           'realizo',
           'talca',
           'vehiculos'},
          {'233', 'mas', 'minutos', 'solo', 'video', 'videos', 'vistos',
           'youtube'},
          {'cristiano', 'debate', 'estatua', 'ronaldo', 'torno'},
          {'bryant', 'golden', 'kobe', 'lakers', 'sorprendieron', 'state'},
          {'juicio', 'larrain', 'martin', 'ministerio', 'nuevo', 'probable',
           'publico'},
          {'audio', 'earned', 'grey', 'oficial', 'primer', 'sombras', 'tema'},
          {'esquiador', 'estilo', 'extremo', 'pelicula', 'video', 'vuela'},
          {'advierte', 'datos', 'difusion', 'robados', 'sony', 'twitter'},
          {'chileno', 'deporte', 'pascuero', 'pides', 'responde', 'viejo'},
          {'cut', 'empresarios', 'iban', 'laboral', 'obviamente', 'oponer',
           'reforma'},
          {'celebrando', 'cumpleanos', 'fotos', 'rindieron', 'salas',
           'tributo'},
          {'anos', 'best', 'buddies', 'cornu', 'fundacion', 'maria', 'refirio',
           'rosa'},
          {'aca', 'gracias', 'junto', 'proxima', 'viejito', 'visitarnos'},
          {'conversar', 'estudios', 'pascuero', 'viejo'},
          {'breve', 'conversa', 'deseos', 'envia', 'navidenos', 'preguntas'},
          {'breve', 'conversa', 'deseos', 'envia', 'navidenos', 'preguntas'},
          {'ahora',
           'avances',
           'conversamos',
           'creditos',
           'diferencias',
           'economia',
           'efectivo',
           'ministro',
           'torno'},
          {'conversar', 'envia', 'estudios', 'preguntas', 'regresa'},
          {'bells',
           'famoso',
           'impensadas',
           'interpretaciones',
           'jingle',
           'raras',
           'recopilacion',
           'videos'},
          {'adaptando', 'perfil'},
          {'and',
           'christmas',
           'get',
           'hat',
           'head',
           'into',
           'put',
           'santa',
           'spirit',
           'the',
           'this',
           'your'},
          {'arbol',
           'envianos',
           'familia',
           'foto',
           'junto',
           'mostraremos',
           'navidad',
           'pantalla'},
          {'100',
           'anos',
           'dia',
           'especial',
           'guerra',
           'mas',
           'mundial',
           'navidad',
           'primera',
           'puede',
           'tregua'},
          {'alvarez',
           'asesinado',
           'concepcion',
           'espanol',
           'forense',
           'homicidio',
           'informe',
           'intendente',
           'osamentas',
           'paginas',
           'perito'},
          {'bachelet',
           'enero',
           'francisco',
           'oficial',
           'papa',
           'presidenta',
           'recibida',
           'sera'},
          {'600', 'carlos', 'hijas', 'indemnizara', 'millones', 'prats'},
          {'hospitalizaron', 'padre', 'problemas', 'respiratorios'},
          {'2017', 'diputada', 'presentara'},
          {'600', 'carlos', 'hijas', 'indemnizara', 'millones', 'prats'},
          {'hospitalizaron', 'padre', 'problemas', 'respiratorios'},
          {'2017', 'diputada', 'presentara'},
          {'acumulados',
           'anos',
           'beneficios',
           'depositaran',
           'hoy',
           'jovenes',
           'mujeres',
           'reclamados',
           'sido'},
          {'600', 'carlos', 'hijas', 'indemnizara', 'millones', 'prats'},
          {'hospitalizaron', 'padre', 'problemas', 'respiratorios'},
          {'2017', 'diputada', 'presentara'},
          {'425', 'chile', 'menos', 'mensuales', 'mil', 'pesos', 'vive'},
          {'cadem',
           'candidatos',
           'destacan',
           'encuesta',
           'enriquezominami',
           'marco',
           'mejores',
           'pinera',
           'sebastian'},
          {'cerca',
           'cierto',
           'detectaron',
           'estudian',
           'examenes',
           'ninos',
           'plomo',
           'puerto',
           'sangre',
           'triste'},
          {'600', 'carlos', 'hijas', 'indemnizara', 'millones', 'prats'},
          {'hospitalizaron', 'padre', 'problemas', 'respiratorios'},
          {'2017', 'diputada', 'presentara'},
          {'600', 'carlos', 'hijas', 'indemnizara', 'millones', 'prats'},
          {'hospitalizaron', 'padre', 'problemas', 'respiratorios'},
          {'2017', 'diputada', 'presentara'},
          {'600', 'carlos', 'hijas', 'indemnizara', 'millones', 'prats'},
          {'hospitalizaron', 'padre', 'problemas', 'respiratorios'},
          {'2017', 'diputada', 'presentara'},
          {'00hrs',
           'centro',
           'desea',
           'diario',
           'especialmente',
           'excelente',
           'felicidades',
           'onomastico',
           'saluda'}]

    a, b = get_tweets_keywords(T2)
    print a
    print b


if __name__ == '__main__':
    main()
